apiVersion: kustomize.config.k8s.io/v1beta1
namespace: bookinfo
kind: Kustomization
resources:
- https://raw.githubusercontent.com/istio/istio/1.8.2/samples/bookinfo/platform/kube/bookinfo.yaml
helmChartInflationGenerator:
- chartRepoUrl: https://raw.githubusercontent.com/moondev/echo-chart/main
  chartName: echo
  valuesLocal:
    items:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: bookinfo
        labels:
          istio-injection: enabled
