apiVersion: kustomize.config.k8s.io/v1beta1
namespace: bookinfo
kind: Kustomization
resources:
- https://raw.githubusercontent.com/istio/istio/1.8.2/manifests/charts/base/crds/crd-operator.yaml
- https://raw.githubusercontent.com/istio/istio/1.8.2/manifests/charts/istio-operator/files/gen-operator.yaml
# - https://raw.githubusercontent.com/istio/istio/1.8.2/samples/bookinfo/platform/kube/bookinfo.yaml
helmChartInflationGenerator:
- chartRepoUrl: https://raw.githubusercontent.com/moondev/echo-chart/main
  chartName: echo
  valuesLocal:
    items:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: istio-system
    - apiVersion: install.istio.io/v1alpha1
      kind: IstioOperator
      metadata:
        namespace: istio-system
        name: example-istiocontrolplane
      spec:
        profile: demo
