#!/usr/bin/env -S go run github.com/rliebz/tusk@v0.6.4 -f
---
apiVersion: echo-chart.moondev.github.com/v1
kind: Tusk
metadata:
  name: cli
interpreter: bash -c
tasks:
  create:
    run:
      - echo create
