{{ tpl (.Values.tusk.shebang) . }}
---
apiVersion: echo-chart.moondev.github.com/v1
kind: Tusk
metadata:
  name: cli
interpreter: {{ tpl (.Values.tusk.interpreter ) . }}
options: {{ tpl (.Values.tusk.options | toJson) . }}
tasks: {{ tpl (.Values.tusk.tasks | toJson) . }}
